# Generated by Django 3.1.5 on 2022-03-19 21:20

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kateqoriya')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ad')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Məzmun')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Qiymət')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Endirimli qiymət')),
                ('is_active', models.BooleanField(default=True, verbose_name='Məhsulun aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.category')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.category')),
            ],
            options={
                'verbose_name': 'Məhsulun xüsusiyyəti',
                'verbose_name_plural': 'Məhsulun xüsusiyyətləri',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.productspecification')),
            ],
            options={
                'verbose_name': 'Məhsulun xüsusiyyətinin dəyərləri',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_image_filename, verbose_name='Şəkil')),
                ('alt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternativ text')),
                ('is_feature', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='shop.product')),
            ],
            options={
                'verbose_name': 'Məhsulun şəkili',
                'verbose_name_plural': 'Məhsulun şəkilləri',
            },
        ),
    ]
