# Generated by Django 3.1.5 on 2022-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220321_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
