# Generated by Django 3.1.5 on 2022-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220320_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
