# Generated by Django 3.1.5 on 2022-03-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
